services:
  - type: web
    name: chemical-equipment-api
    env: python
    plan: free
    # This is the key change:
    rootDir: backend 
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate --no-input
    # No 'cd' needed here now because we are already in /backend
    startCommand: gunicorn chemical_visualizer.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG_MODE
        value: "True"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: chemical-equipment-db
          property: connectionString