services:
  - type: web
    name: chemical-equipment-api
    env: python
    plan: free
    rootDir: backend 
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate --no-input
    startCommand: gunicorn chemical_visualizer.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG_MODE
        value: "False" 
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: chemical-equipment-db
          property: connectionString

databases:
  - name: chemical-equipment-db
    databaseName: chemical_db
    user: chemical_user
    plan: free